@startuml
package DocumentStore {
  component document_index_1
  component document_index_2
  component label_index_1
  component label_index_2
  component label_index_3
}

label_index_1 -> document_index_1: "documents"
label_index_2 -> document_index_1: "documents"
label_index_3 -> document_index_2: "documents"
@enduml
