@startuml
package DocumentStore {
  database doc_1
  database doc_2
  database doc_n
  database label_1
  database label_2
  database label_3
  database label_k
}

label_1 -up-> doc_1: "documents"
label_2 -up-> doc_1: "documents"
label_3 -up-> doc_2: "documents"
@enduml
