@startuml
package DocumentStore {
  component document_index_1
  component document_index_2
  component document_index_n
  component label_index_1
  component label_index_2
  component label_index_3
  component label_index_j
}

label_index_1 --> document_index_1
label_index_2 --> document_index_1
label_index_3 --> document_index_2
@enduml
