@startuml
actor User
User -> DocumentStore: add_eval_data(SQuAD_file)
DocumentStore --> Preprocessor: preprocess Context
Preprocessor --> DocumentStore: Documents
DocumentStore --> DocumentStore: generate Labels
DocumentStore --> DocumentIndex: write Documents
DocumentIndex --> DocumentStore
DocumentStore --> LabelIndex: write Labels
LabelIndex --> DocumentStore
DocumentStore --> User
@enduml
