@startuml
actor User
User -> DocumentStore: get_all_labels_aggregated()
DocumentStore --> LabelIndex: get Labels
LabelIndex --> DocumentStore: Labels
DocumentStore --> DocumentStore: aggregate Labels
DocumentStore --> User: MultiLabels
User --> Pipeline: eval(MultiLabels)
Pipeline --> DocumentStore: query
DocumentStore --> DocumentIndex: query
DocumentIndex --> DocumentStore: result
DocumentStore --> Pipeline: result
Pipeline --> User: EvaluationResult
@enduml
